/* Allegro datafile object indexes, produced by grabber v3.0 */
/* Datafile: c:\ray\dat1.dat */
/* Date: Mon Apr 26 22:39:53 1999 */
/* Do not hand edit! */

#define DAT1__PAL                        0        /* PAL  */
#define DAT1_FLOOR_01                    1        /* BMP  */
#define DAT1_FLOOR_02                    2        /* BMP  */
#define DAT1_FLOOR_03                    3        /* BMP  */
#define DAT1_FLOOR_04                    4        /* BMP  */
#define DAT1_FLOOR_05                    5        /* BMP  */
#define DAT1_WALL_01                     6        /* BMP  */
#define DAT1_WALL_02                     7        /* BMP  */
#define DAT1_WALL_03                     8        /* BMP  */
#define DAT1_WALL_04                     9        /* BMP  */
#define DAT1_WALL_05                     10       /* BMP  */
#define DAT1_WALL_06                     11       /* BMP  */
#define DAT1_WALL_07                     12       /* BMP  */
#define DAT1_WALL_08                     13       /* BMP  */
#define DAT1_WALL_09                     14       /* BMP  */
#define DAT1_WALL_10                     15       /* BMP  */
#define DAT1_WALL_11                     16       /* BMP  */
#define DAT1_WALL_12                     17       /* BMP  */
#define DAT1_WALL_13                     18       /* BMP  */
#define DAT1_WALL_14                     19       /* BMP  */
#define DAT1_WALL_15                     20       /* BMP  */
#define DAT1_COUNT                       21

